### ISSUE TITLE
Compatibility with Discourse v2.2.0.beta2

### ISSUE THREAD

**Issue by NicolasMahe** [nskerl/discourse-sequence-diagram#1]
Hello,

I would like to use this plugin on my Discourse v2.2.0.beta2 but I cannot make it work.

I added your plugin's git in the file `containers/app.yml`:
```yml
## Plugins go here
## see https://meta.discourse.org/t/19157 for details
hooks:
  after_code:
    - exec:
        cd: $home/plugins
        cmd:
          - git clone https://github.com/discourse/docker_manager.git
          - git clone https://github.com/nskerl/discourse-sequence-diagram.git
```
And then rebuild the app.

I can then see the plugin in the Admin/Plugins page and the setting "diagrams plugin enabled" is checked.

But when I put the following code in a post, the code is not transformed as a diagram.

```
[seqdiagram]
A->B:one
B->A:two
[/seqdiagram]
```

You can see the post here: https://forum.mesg.com/t/test-sequence-diagram/66

Did I miss something during the installation or configuration of the plugin?

Thank you for making this plugin and for any help you can provide.
